swagger: "2.0"
info:
 version: "1.0.0"
 title: "Aanvragen applicatie API"
 description: "API voor het beheren van aanvragen ingediend via de Aanvragen applicatie"
 contact:
   name: "Team Aanvragen"
   email: "team.aanvragen@randstadgroep.nl"
   url: "https://aanvragen.randstad.nl/contact"
host: "localhost:9000"
schemes:
 - "http"
consumes:
 - "application/json"
produces:
 - "application/json"
paths:
 /v3/aanvragen/{id}:
   get:
     tags:
       - "Aanvraag"
     description: "Lees de aanvraag"
     operationId: "controllers.AanvragenControllerV3.leesAanvraag(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
     responses:
       200:
         description: "aanvraag gevonden en OK"
       404:
         description: "aanvraag bestaat niet of is verwijderd"
       default:
         description: "unexpected error"
   post:
     tags:
       - "Aanvraag"
     description: "Update de aanvraag"
     operationId: "controllers.AanvragenControllerV3.update(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
       -
         name: "request"
         in: body
         description: "de update aanvraag request"
         required: true
         schema:
           $ref: '#/definitions/UpdateAanvraagRequest'
     responses:
       200:
         description: "aanvraag geupdate en OK"
         schema:
           $ref: '#/definitions/UpdateAanvraagResponse'
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/uuid/{uuid}:
   get:
     tags:
       - "Aanvraag"
     description: "Lees de aanvraag met UUID"
     operationId: "controllers.AanvragenControllerV3.leesAanvraagMetUUID(uuid:String)"
     produces:
       - "json"
     parameters:
       -
         name: "uuid"
         in: "path"
         description: "aanvraagUuid"
         required: true
         type: "integer"
     responses:
       200:
         description: "aanvraag gevonden en OK"
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/gm/{gmAanvraagNummer}:
   get:
     tags:
       - "Aanvraag"
     description: "Lees de aanvraag met het gm aanvraagNummer"
     operationId: "controllers.AanvragenControllerV3.leesAanvraagMetGmAanvraagNummer(gmAanvraagNummer:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "gmAanvraagNummer"
         in: "path"
         description: "gm aanvraag nummer"
         required: true
         type: "integer"
     responses:
       200:
         description: "aanvraag gevonden en OK"
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen:
   get:
     tags:
       - "Aanvraag"
     description: "Geef alle aanvragen met de opgegeven status behorende bij de opgegeven invoerUnit"
     operationId: "controllers.AanvragenControllerV3.geefAanvragen(invoerUnit:Int, status:Option[String])"
     produces:
       - "json"
     parameters:
       -
         name: "invoerUnit"
         in: "query"
         description: "id van de invoerunit"
         required: true
         type: "integer"
       -
         name: "status"
         in: "query"
         description: "status van de aanvraag"
         required: false
         type: "string"
     responses:
       200:
         description: "OK"
       default:
         description: "unexpected error"
   post:
     tags:
       - "Aanvraag"
     description: "Maak een nieuwe aanvraag aan"
     operationId: "controllers.AanvragenControllerV3.newAanvraag()"
     produces:
       - "json"
     parameters:
       -
         name: "request"
         in: body
         description: "de insert nieuwe aanvraag request"
         required: true
         schema:
           $ref: '#/definitions/NewAanvraagRequest'
     responses:
       200:
         description: "Nieuwe aanvraag aangemaakt en OK"
       default:
         description: "unexpected error"
 /v3/aanvragen/verstuurd:
   get:
     tags:
       - "Aanvraag"
     description: "Geef alle verstuurde aanvragen van de opgegeven invoerUnit"
     operationId: "controllers.AanvragenControllerV3.verstuurdeAanvragen(invoerUnit:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "invoerUnit"
         in: "query"
         description: "id van de invoerunit"
         required: true
         type: "integer"
     responses:
       200:
         description: "OK"
       default:
         description: "unexpected error"
 /v3/aanvragen/ontvangen:
   get:
     tags:
       - "Aanvraag"
     description: "Geef alle ontvangen aanvragen van de opgegeven meezoekUnit"
     operationId: "controllers.AanvragenControllerV3.ontvangenAanvragen(meezoekUnit:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "meezoekUnit"
         in: "query"
         description: "id van de meezoekUnit"
         required: true
         type: "integer"
     responses:
       200:
         description: "OK"
       default:
         description: "unexpected error"
 /v3/aanvragen/ontvangen/aantal:
   get:
     tags:
       - "Aanvraag"
     description: "Geef het aantal ontvangen aanvragen van de opgegeven meezoekUnit, die zijn ontvangen na de vanafDatumTijd"
     operationId: "controllers.AanvragenControllerV3.aantalOntvangenAanvragen(meezoekUnit:Int, vanafDatumTijd: String)"
     produces:
       - "json"
     parameters:
       -
         name: "meezoekUnit"
         in: "query"
         description: "id van de meezoekUnit"
         required: true
         type: "integer"
       -
          name: "vanafDatumTijd"
          in: query
          description: "de vanafDatumTijd bv. 2016-01-01T00:00:00"
          required: true
          type: "string"
          format: date-time
     responses:
       200:
         description: "OK"
       default:
         description: "unexpected error"
 /v3/aanvragen/{id}/events:
   get:
     tags:
       - "Aanvraag"
     description: "Geef events van de aanvraag"
     operationId: "controllers.AanvragenControllerV3.geefEvents(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
     responses:
       200:
         description: "aanvraag gevonden en OK"
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/{id}/indienen:
   post:
     tags:
       - "Aanvraag"
     description: "Indienen van de aanvraag"
     operationId: "controllers.AanvragenControllerV3.indienen(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
       -
         name: "request"
         in: body
         description: "de insert nieuwe aanvraag request"
         required: true
         schema:
           $ref: '#/definitions/IndienenAanvraagRequest'
     responses:
       200:
         description: "aanvraag ingediend en OK"
         schema:
           $ref: '#/definitions/IndienenResponse'
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/{id}/copy:
   post:
     tags:
       - "Aanvraag"
     description: "Kopiëren van de aanvraag"
     operationId: "controllers.AanvragenControllerV3.copy(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
       -
         name: "request"
         in: body
         description: "het kopiëren van een aanvraag request"
         required: true
         schema:
           $ref: '#/definitions/CopyAanvraagRequest'
     responses:
       200:
         description: "aanvraag gekopiëerd en OK"
         schema:
           $ref: '#/definitions/CopyAanvraagResponse'
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/{id}/verwijder:
   post:
     tags:
       - "Aanvraag"
     description: "Verwijderen van de aanvraag"
     operationId: "controllers.AanvragenControllerV3.verwijder(id:Int)"
     produces:
       - "json"
     parameters:
       -
         name: "id"
         in: "path"
         description: "aanvraagId"
         required: true
         type: "integer"
       -
         name: "request"
         in: body
         description: "het verwijderen van een aanvraag request"
         required: true
         schema:
           $ref: '#/definitions/VerwijderAanvraagRequest'
     responses:
       200:
         description: "aanvraag verwijderd en OK"
         schema:
           $ref: '#/definitions/VerwijderenResponse'
       404:
         description: "aanvraag niet gevonden"
       default:
         description: "unexpected error"
 /v3/aanvragen/csv:
   get:
     tags:
       - "Aanvraag"
       - "Csv"
     description: "Geef een csv bestand van alle verstuurde aanvragen"
     operationId: "controllers.AanvragenControllerV3.csv()"
     produces:
       - "application/octet-stream"
     parameters:
       -
        name: "startdatum"
        in: query
        description: "de startdatum bv. 2016-01-01T00:00:00"
        required: false
        type: "string"
        format: date-time
       -
        name: "einddatum"
        in: query
        description: "de einddatum bv. 2016-06-01T00:00:00"
        required: false
        type: "string"
        format: date-time

     responses:
        200:
          description: "csv file"
          schema:
            type: file
        default:
           description: "unexpected error"
 /v3/aanvragen/csv/taxonomy:
   get:
     tags:
       - "Taxonomy"
       - "Csv"
     description: "Geef een csv bestand voor taxonomy van alle verstuurde aanvragen"
     operationId: "controllers.AanvragenControllerV3.taxonomyCsv()"
     produces:
       - "application/octet-stream"
     parameters:
       -
        name: "startdatum"
        in: query
        description: "de startdatum bv. 2016-01-01T00:00:00"
        required: false
        type: "string"
        format: date-time
       -
        name: "einddatum"
        in: query
        description: "de einddatum bv. 2016-06-01T00:00:00"
        required: false
        type: "string"
        format: date-time
     responses:
        200:
          description: "csv file"
          schema:
            type: file
        default:
           description: "unexpected error"
 /v1/verstuurMail:
  post:
    tags:
      -   "Mail"
    description: "Verstuur een mail."
    operationId: "controllers.MailControllerV1.verstuurMail()"
    produces:
           - "json"
    parameters:
           -
             name: "request"
             in: body
             description: "de mail request"
             required: true
             schema:
               $ref: '#/definitions/NewMailRequest'
    responses:
           200:
             description: "Nieuwe mail verstuurd en OK"
           default:
             description: "unexpected error"
 /v1/{gwm}/prijsVariabelen/{taxoFunctieCode}:
  get:
    tags:
     -   "Pricing"
    description: "Lees prijs variabelen voor een Taxonomy Functie"
    operationId: "controllers.PricingController.prijsVariabelenPerTaxoFunctie"
    produces:
          - "json"
    parameters:
            -
             name: "gwm"
             in: path
             description: "gwm afkorting (rnl of ttg)"
             required: true
             type: "string"
            -
             name: "taxoFunctieCode"
             in: path
             description: "taxonomy code behorende bij de functie"
             required: true
             type: "integer"
    responses:
           200:
             description: "prijs variabelen gevonden en OK"
           default:
             description: "unexpected error"
 /v1/dataDump:
   post:
     tags:
       - "Datadump"
     description: "Verwerk datadump"
     operationId: "controllers.DataDumpControllerV1.verwerkDataDump()"
     produces:
       - "json"
     parameters:
      -
        name: "request"
        in: body
        description: "de request"
        required: true
        schema:
           $ref: '#/definitions/DataDumpRequest'
     responses:
       200:
         description: "Verwerken datadump gestart en OK"
         schema:
            $ref: "#/definitions/DataDumpResponse"
       default:
         description: "unexpected error"
definitions:
  UpdateAanvraagRequest:
    type: object
    properties:
      bewerkendeGebruikerQuantumId:
        type: string
      bewerkendeUnit:
        type: integer
      versieNummer:
        type: integer
      aanvraagDetails:
        type: object
  NewAanvraagRequest:
    type: object
    properties:
      bewerkendeUnit:
        type: integer
  IndienenAanvraagRequest:
    type: object
    properties:
      bewerkendeUnit:
        type: integer
      versieNummer:
        type: integer
  CopyAanvraagRequest:
    type: object
    properties:
      id:
        type: integer
  VerwijderAanvraagRequest:
    type: object
    properties:
      bewerkendeUnit:
        type: integer
  NewMailRequest:
    type: object
    required: [afzender, toOntvangers, onderwerp, inhoud]
    properties:
      afzender:
        $ref: "#/definitions/EmailAdres"
      replyTo:
        $ref: "#/definitions/EmailAdresArray"
      toOntvangers:
        $ref: "#/definitions/EmailAdresArray"
      ccOntvangers:
        $ref: "#/definitions/EmailAdresArray"
      onderwerp:
        type: string
      inhoud:
        type: string
  EmailAdres:
    type: object
    required: [adres]
    properties:
      naam:
        type: string
      adres:
        type: string
  EmailAdresArray:
    type: array
    items:
      $ref: "#/definitions/EmailAdres"
  CopyAanvraagResponse:
    type: object
    properties:
      id:
        type: integer
  UpdateAanvraagResponse:
    type: object
    properties:
      message:
        type: string
  IndienenResponse:
    type: object
    properties:
      message:
        type: string
  VerwijderenResponse:
    type: object
    properties:
      message:
        type: string
  DataDumpRequest:
    type: object
    properties:
      url:
        type: string
      handlerId:
        type: string
      uitvoerder:
        type: string
      deleteAll:
        type: boolean
  DataDumpResponse:
    type: object
    properties:
      aantalVerwerkt:
        type: integer
      aantalFout:
        type: integer
      errorList:
        type: array
        "items": {
              "$ref": "#/definitions/DataDumpErrorMessage"
            }
  DataDumpErrorMessage:
    type: object